module.exports = {
  url1:  'http://desenvolvimento:8082/homologacao1/admin/default.aspx#/dashboard',
  url2:  'http://desenvolvimento:8082/homologacao2/admin/default.aspx#/dashboard',
  url3:  'http://desenvolvimento:8082/homologacao3/admin/default.aspx#/dashboard',
  url4:  'http://desenvolvimento:8082/homologacao4/admin/default.aspx#/dashboard',
  url5:  'http://desenvolvimento:8082/homologacao5/admin/default.aspx#/dashboard',
  url6:  'http://desenvolvimento:8082/homologacao6/admin/default.aspx#/dashboard',
  url7:  'http://desenvolvimento:8082/homologacao7/admin/default.aspx#/dashboard',
  url8:  'http://desenvolvimento:8082/homologacao8/admin/default.aspx#/dashboard',
  url9:  'http://desenvolvimento:8082/homologacao9/admin/default.aspx#/dashboard',
  url10: 'http://desenvolvimento:8082/homologacao10/admin/default.aspx#/dashboard',
  url11: 'http://desenvolvimento:8082/homologacao11/admin/default.aspx#/dashboard',
  url12: 'http://desenvolvimento:8082/homologacao12/admin/default.aspx#/dashboard',
  url13: 'http://desenvolvimento:8082/homologacao13/admin/default.aspx#/dashboard',
  url14: 'http://desenvolvimento:8082/homologacao14/admin/default.aspx#/dashboard',
  url15: 'http://desenvolvimento:8082/homologacao15/admin/default.aspx#/dashboard',
  url16: 'http://desenvolvimento:8082/homologacao16/admin/default.aspx#/dashboard',
  url17: 'http://desenvolvimento:8082/homologacao17/admin/default.aspx#/dashboard',
  url18: 'http://desenvolvimento:8082/homologacao18/admin/default.aspx#/dashboard',
  url19: 'http://desenvolvimento:8082/homologacao19/admin/default.aspx#/dashboard',
  url20: 'http://desenvolvimento:8082/homologacao20/admin/default.aspx#/dashboard',
  url21: 'http://desenvolvimento:8082/homologacao21/admin/default.aspx#/dashboard',
  url22: 'http://desenvolvimento:8082/homologacao22/admin/default.aspx#/dashboard',
  url23: 'http://desenvolvimento:8082/homologacao23/admin/default.aspx#/dashboard',
  url24: 'http://desenvolvimento:8082/homologacao24/admin/default.aspx#/dashboard',
  url25: 'http://desenvolvimento:8082/homologacao25/admin/default.aspx#/dashboard'
}
